# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         TM-Virtual-DNS
version:      0.10
version_from: lib/TM/Virtual/DNS.pm
installdirs:  site
requires:
    Log::Log4perl:                 0.5
    Net::DNS:                      0.19
    Test::Deep:                    0.093
    Test::More:                    0.47
    Test::Pod:                     1
    TM:                            1.23

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
